// GENERATED by scripts/build-props.mjs from scripts/props.config.mjs — do not edit.
// Sizes are metres; each prop's base is centred on its origin, front facing +z.

export type PropId =
  | 'shop-a'
  | 'shop-b'
  | 'shop-c'
  | 'shop-d'
  | 'shop-e'
  | 'shop-f'
  | 'shop-g'
  | 'shop-h'
  | 'shop-k'
  | 'shop-l'
  | 'house-a'
  | 'house-b'
  | 'house-c'
  | 'house-d'
  | 'house-e'
  | 'house-f'
  | 'house-h'
  | 'house-k'
  | 'lamp'
  | 'lamp-curved'
  | 'traffic-light'
  | 'barrier'
  | 'cone'
  | 'dumpster'
  | 'sign-stop'
  | 'fence'
  | 'fence-low'
  | 'planter'
  | 'tree-street'
  | 'factory-a'
  | 'factory-b'
  | 'factory-c'
  | 'factory-d'
  | 'factory-e'
  | 'factory-f'
  | 'chimney'
  | 'chimney-medium'
  | 'tank-large'
  | 'tank'
  | 'water-tower'
  | 'tree-oak'
  | 'tree-default'
  | 'tree-detailed'
  | 'tree-fat'
  | 'tree-tall'
  | 'tree-pine-tall-a'
  | 'tree-pine-round-c'
  | 'tree-cone'
  | 'rock-a'
  | 'rock-b'
  | 'rock-c'
  | 'rock-d'
  | 'rock-e'
  | 'rock-f'
  | 'rock-tall-a'
  | 'rock-tall-c'
  | 'rock-tall-e'
  | 'log-stack'
  | 'log'
  | 'stump'
  | 'bush'
  | 'bush-small'
  | 'tent'
  | 'campfire'
  | 'fence-wood';

export type PropTag = 'building' | 'house' | 'street' | 'cover' | 'small' | 'fence' | 'tree' | 'factory' | 'industrial' | 'rock' | 'nature';

export interface PropCollider { dx: number; dz: number; y: number; w: number; d: number; h: number; blocks?: 'shots' }

export interface PropInfo {
  w: number;
  d: number;
  h: number;
  tags: readonly PropTag[];
  /** Collision boxes relative to the base centre (before rotation) */
  colliders: readonly PropCollider[];
  /** Average colour, for the map preview */
  color: number;
}

export const PROPS: Record<PropId, PropInfo> = {
  'shop-a': {
    w: 7.07,
    d: 7.52,
    h: 10.34,
    tags: [
      'building'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 7.07,
        d: 7.52,
        h: 10.34
      }
    ],
    color: 7896465
  },
  'shop-b': {
    w: 7.76,
    d: 7.52,
    h: 10.34,
    tags: [
      'building'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 7.76,
        d: 7.52,
        h: 10.34
      }
    ],
    color: 7896209
  },
  'shop-c': {
    w: 7.07,
    d: 8.72,
    h: 7.14,
    tags: [
      'building'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 7.07,
        d: 8.72,
        h: 7.14
      }
    ],
    color: 8029076
  },
  'shop-d': {
    w: 6.72,
    d: 7.2,
    h: 10.34,
    tags: [
      'building'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 6.72,
        d: 7.2,
        h: 10.34
      }
    ],
    color: 7568780
  },
  'shop-e': {
    w: 13.12,
    d: 8.06,
    h: 7.14,
    tags: [
      'building'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 13.12,
        d: 8.06,
        h: 7.14
      }
    ],
    color: 7962515
  },
  'shop-f': {
    w: 6.72,
    d: 8.24,
    h: 13.54,
    tags: [
      'building'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 6.72,
        d: 8.24,
        h: 13.54
      }
    ],
    color: 7700368
  },
  'shop-g': {
    w: 7.76,
    d: 7.38,
    h: 13.54,
    tags: [
      'building'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 7.76,
        d: 7.38,
        h: 13.54
      }
    ],
    color: 7961742
  },
  'shop-h': {
    w: 7.07,
    d: 8.06,
    h: 10.34,
    tags: [
      'building'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 7.07,
        d: 8.06,
        h: 10.34
      }
    ],
    color: 7238794
  },
  'shop-k': {
    w: 16.67,
    d: 7.54,
    h: 11.76,
    tags: [
      'building'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 16.67,
        d: 7.54,
        h: 11.76
      }
    ],
    color: 8093071
  },
  'shop-l': {
    w: 10.96,
    d: 11.22,
    h: 18.16,
    tags: [
      'building'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 10.96,
        d: 11.22,
        h: 18.16
      }
    ],
    color: 7831185
  },
  'house-a': {
    w: 8.84,
    d: 6.99,
    h: 5.67,
    tags: [
      'building',
      'house'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 8.84,
        d: 6.99,
        h: 5.67
      }
    ],
    color: 7836563
  },
  'house-b': {
    w: 12.43,
    d: 7.75,
    h: 7.74,
    tags: [
      'building',
      'house'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 12.43,
        d: 7.75,
        h: 7.74
      }
    ],
    color: 7703953
  },
  'house-c': {
    w: 8.75,
    d: 6.99,
    h: 7.03,
    tags: [
      'building',
      'house'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 8.75,
        d: 6.99,
        h: 7.03
      }
    ],
    color: 8098454
  },
  'house-d': {
    w: 11.94,
    d: 6.99,
    h: 8.42,
    tags: [
      'building',
      'house'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 11.94,
        d: 6.99,
        h: 8.42
      }
    ],
    color: 8163478
  },
  'house-e': {
    w: 8.84,
    d: 6.99,
    h: 7.74,
    tags: [
      'building',
      'house'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 8.84,
        d: 6.99,
        h: 7.74
      }
    ],
    color: 7834258
  },
  'house-f': {
    w: 9.71,
    d: 9.56,
    h: 7.74,
    tags: [
      'building',
      'house'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 9.71,
        d: 9.56,
        h: 7.74
      }
    ],
    color: 7769490
  },
  'house-h': {
    w: 8.84,
    d: 6.23,
    h: 5.01,
    tags: [
      'building',
      'house'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 8.84,
        d: 6.23,
        h: 5.01
      }
    ],
    color: 7833490
  },
  'house-k': {
    w: 6.26,
    d: 6.94,
    h: 7.82,
    tags: [
      'building',
      'house'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 6.26,
        d: 6.94,
        h: 7.82
      }
    ],
    color: 7833490
  },
  lamp: {
    w: 0.4,
    d: 1.9,
    h: 4.8,
    tags: [
      'street'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 0.3,
        d: 0.3,
        h: 4.5
      }
    ],
    color: 15460077
  },
  'lamp-curved': {
    w: 0.4,
    d: 1.8,
    h: 5.4,
    tags: [
      'street'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 0.3,
        d: 0.3,
        h: 4.5
      }
    ],
    color: 15592176
  },
  'traffic-light': {
    w: 0.94,
    d: 0.72,
    h: 4.12,
    tags: [
      'street'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 0.35,
        d: 0.35,
        h: 4
      }
    ],
    color: 12301491
  },
  barrier: {
    w: 1.08,
    d: 1.8,
    h: 1.04,
    tags: [
      'street',
      'cover'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 1.08,
        d: 1.8,
        h: 1.04
      }
    ],
    color: 14277095
  },
  cone: {
    w: 0.6,
    d: 0.6,
    h: 0.75,
    tags: [
      'street',
      'small'
    ],
    colliders: [],
    color: 15099981
  },
  dumpster: {
    w: 2.2,
    d: 2.96,
    h: 1.68,
    tags: [
      'street',
      'cover'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 2.2,
        d: 2.96,
        h: 1.68
      }
    ],
    color: 12297058
  },
  'sign-stop': {
    w: 0.62,
    d: 1.11,
    h: 3.95,
    tags: [
      'street'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 0.2,
        d: 0.2,
        h: 2.5
      }
    ],
    color: 14663099
  },
  fence: {
    w: 8.67,
    d: 2.97,
    h: 1.84,
    tags: [
      'fence'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 8.67,
        d: 2.97,
        h: 1.84
      }
    ],
    color: 13926235
  },
  'fence-low': {
    w: 8.67,
    d: 5.69,
    h: 1.16,
    tags: [
      'fence'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 8.67,
        d: 5.69,
        h: 1.16
      }
    ],
    color: 14123356
  },
  planter: {
    w: 2.72,
    d: 2.04,
    h: 1.2,
    tags: [
      'cover'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 2.72,
        d: 2.04,
        h: 1.2
      }
    ],
    color: 6461826
  },
  'tree-street': {
    w: 1.43,
    d: 1.65,
    h: 5.22,
    tags: [
      'tree'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 0.45,
        d: 0.45,
        h: 2.6
      },
      {
        dx: 0,
        dz: 0,
        y: 2.21,
        w: 1,
        d: 1.16,
        h: 3.01,
        blocks: 'shots'
      }
    ],
    color: 8166000
  },
  'factory-a': {
    w: 15,
    d: 8.94,
    h: 10.58,
    tags: [
      'building',
      'factory'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 15,
        d: 8.94,
        h: 10.58
      }
    ],
    color: 13269593
  },
  'factory-b': {
    w: 15,
    d: 9.09,
    h: 10.58,
    tags: [
      'building',
      'factory'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 15,
        d: 9.09,
        h: 10.58
      }
    ],
    color: 13336929
  },
  'factory-c': {
    w: 13.51,
    d: 15.18,
    h: 9,
    tags: [
      'building',
      'factory'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 13.51,
        d: 15.18,
        h: 9
      }
    ],
    color: 13469295
  },
  'factory-d': {
    w: 6.36,
    d: 10.22,
    h: 10.18,
    tags: [
      'building',
      'factory'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 6.36,
        d: 10.22,
        h: 10.18
      }
    ],
    color: 13204057
  },
  'factory-e': {
    w: 12.12,
    d: 9.29,
    h: 11.88,
    tags: [
      'building',
      'factory'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 12.12,
        d: 9.29,
        h: 11.88
      }
    ],
    color: 13598814
  },
  'factory-f': {
    w: 12.89,
    d: 9.22,
    h: 13.86,
    tags: [
      'building',
      'factory'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 12.89,
        d: 9.22,
        h: 13.86
      }
    ],
    color: 13139035
  },
  chimney: {
    w: 8.64,
    d: 8.64,
    h: 13.6,
    tags: [
      'industrial'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 8.64,
        d: 8.64,
        h: 13.6
      }
    ],
    color: 13804180
  },
  'chimney-medium': {
    w: 3.6,
    d: 3.6,
    h: 15.4,
    tags: [
      'industrial'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 3.6,
        d: 3.6,
        h: 15.4
      }
    ],
    color: 12295334
  },
  'tank-large': {
    w: 12.07,
    d: 13.19,
    h: 7.69,
    tags: [
      'industrial'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 12.07,
        d: 13.19,
        h: 7.69
      }
    ],
    color: 14066058
  },
  tank: {
    w: 6.78,
    d: 4.12,
    h: 3.32,
    tags: [
      'industrial'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 6.78,
        d: 4.12,
        h: 3.32
      }
    ],
    color: 13208966
  },
  'water-tower': {
    w: 6.82,
    d: 6.65,
    h: 17.13,
    tags: [
      'industrial'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 6.82,
        d: 6.65,
        h: 17.13
      }
    ],
    color: 12155748
  },
  'tree-oak': {
    w: 3.68,
    d: 4.25,
    h: 7.05,
    tags: [
      'tree'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 0.5,
        d: 0.5,
        h: 3
      },
      {
        dx: 0,
        dz: 0,
        y: 2.55,
        w: 2.58,
        d: 2.98,
        h: 4.5,
        blocks: 'shots'
      }
    ],
    color: 12505787
  },
  'tree-default': {
    w: 4.34,
    d: 3.76,
    h: 9.82,
    tags: [
      'tree'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 0.5,
        d: 0.5,
        h: 3
      },
      {
        dx: 0,
        dz: 0,
        y: 2.55,
        w: 3.04,
        d: 2.63,
        h: 7.27,
        blocks: 'shots'
      }
    ],
    color: 12505787
  },
  'tree-detailed': {
    w: 4.87,
    d: 4.38,
    h: 7.66,
    tags: [
      'tree'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 0.5,
        d: 0.5,
        h: 3
      },
      {
        dx: 0,
        dz: 0,
        y: 2.55,
        w: 3.41,
        d: 3.07,
        h: 5.11,
        blocks: 'shots'
      }
    ],
    color: 14082773
  },
  'tree-fat': {
    w: 4.34,
    d: 3.76,
    h: 6.61,
    tags: [
      'tree'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 0.5,
        d: 0.5,
        h: 3
      },
      {
        dx: 0,
        dz: 0,
        y: 2.55,
        w: 3.04,
        d: 2.63,
        h: 4.06,
        blocks: 'shots'
      }
    ],
    color: 12505787
  },
  'tree-tall': {
    w: 2.3,
    d: 2.65,
    h: 9.7,
    tags: [
      'tree'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 0.5,
        d: 0.5,
        h: 3
      },
      {
        dx: 0,
        dz: 0,
        y: 2.55,
        w: 1.61,
        d: 1.86,
        h: 7.15,
        blocks: 'shots'
      }
    ],
    color: 12505787
  },
  'tree-pine-tall-a': {
    w: 2.22,
    d: 2.25,
    h: 8.8,
    tags: [
      'tree'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 0.5,
        d: 0.5,
        h: 3
      },
      {
        dx: 0,
        dz: 0,
        y: 2.55,
        w: 1.55,
        d: 1.58,
        h: 6.25,
        blocks: 'shots'
      }
    ],
    color: 12043197
  },
  'tree-pine-round-c': {
    w: 2.76,
    d: 3.19,
    h: 7.2,
    tags: [
      'tree'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 0.5,
        d: 0.5,
        h: 3
      },
      {
        dx: 0,
        dz: 0,
        y: 2.55,
        w: 1.93,
        d: 2.23,
        h: 4.65,
        blocks: 'shots'
      }
    ],
    color: 12043197
  },
  'tree-cone': {
    w: 3.05,
    d: 3.05,
    h: 8.22,
    tags: [
      'tree'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 0.5,
        d: 0.5,
        h: 3
      },
      {
        dx: 0,
        dz: 0,
        y: 2.55,
        w: 2.13,
        d: 2.13,
        h: 5.67,
        blocks: 'shots'
      }
    ],
    color: 12505787
  },
  'rock-a': {
    w: 5.1,
    d: 6.6,
    h: 1.69,
    tags: [
      'rock'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 4.08,
        d: 5.28,
        h: 1.52
      }
    ],
    color: 12572351
  },
  'rock-b': {
    w: 4.98,
    d: 6.6,
    h: 2.8,
    tags: [
      'rock'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 3.99,
        d: 5.28,
        h: 2.52
      }
    ],
    color: 14149079
  },
  'rock-c': {
    w: 6.92,
    d: 6.6,
    h: 2.09,
    tags: [
      'rock'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 5.53,
        d: 5.28,
        h: 1.88
      }
    ],
    color: 12572351
  },
  'rock-d': {
    w: 6.95,
    d: 6.7,
    h: 3.69,
    tags: [
      'rock'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 5.56,
        d: 5.36,
        h: 3.32
      }
    ],
    color: 14149079
  },
  'rock-e': {
    w: 7.12,
    d: 5.98,
    h: 1.9,
    tags: [
      'rock'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 5.7,
        d: 4.78,
        h: 1.71
      }
    ],
    color: 12572351
  },
  'rock-f': {
    w: 7.12,
    d: 5.84,
    h: 3.11,
    tags: [
      'rock'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 5.7,
        d: 4.67,
        h: 2.8
      }
    ],
    color: 14149079
  },
  'rock-tall-a': {
    w: 6.39,
    d: 4.44,
    h: 6.47,
    tags: [
      'rock'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 4.79,
        d: 3.33,
        h: 5.83
      }
    ],
    color: 14149079
  },
  'rock-tall-c': {
    w: 2.97,
    d: 2.84,
    h: 5.09,
    tags: [
      'rock'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 2.22,
        d: 2.13,
        h: 4.58
      }
    ],
    color: 14149079
  },
  'rock-tall-e': {
    w: 2.97,
    d: 3.42,
    h: 2.88,
    tags: [
      'rock'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 2.22,
        d: 2.57,
        h: 2.6
      }
    ],
    color: 14149079
  },
  'log-stack': {
    w: 3.17,
    d: 3.55,
    h: 1.73,
    tags: [
      'cover',
      'nature'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 3.17,
        d: 3.55,
        h: 1.73
      }
    ],
    color: 15780274
  },
  log: {
    w: 5,
    d: 2.75,
    h: 2.08,
    tags: [
      'cover',
      'nature'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 5,
        d: 2.75,
        h: 2.08
      }
    ],
    color: 16176832
  },
  stump: {
    w: 1.61,
    d: 1.85,
    h: 1.03,
    tags: [
      'nature',
      'small'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 1.61,
        d: 1.85,
        h: 1.03
      }
    ],
    color: 16176832
  },
  bush: {
    w: 1.87,
    d: 1.68,
    h: 1.21,
    tags: [
      'nature',
      'small'
    ],
    colliders: [],
    color: 7597276
  },
  'bush-small': {
    w: 1.98,
    d: 1.98,
    h: 1.22,
    tags: [
      'nature',
      'small'
    ],
    colliders: [],
    color: 7597276
  },
  tent: {
    w: 4.37,
    d: 3.18,
    h: 2.81,
    tags: [
      'nature',
      'cover'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 4.37,
        d: 3.18,
        h: 2.81
      }
    ],
    color: 15769494
  },
  campfire: {
    w: 2.7,
    d: 2.58,
    h: 0.39,
    tags: [
      'nature',
      'small'
    ],
    colliders: [],
    color: 14479860
  },
  'fence-wood': {
    w: 5,
    d: 0.48,
    h: 1.73,
    tags: [
      'fence',
      'nature'
    ],
    colliders: [
      {
        dx: 0,
        dz: 0,
        y: 0,
        w: 5,
        d: 0.48,
        h: 1.73
      }
    ],
    color: 16761765
  }
};
